apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: app-mem
  namespace: aulainfra
spec:
  mode: one
  selector:
    namespaces:
      - aulainfra
    labelSelectors:
      app: app
  stressors:
    memory:
      workers: 1
  duration: 30s
  scheduler:
    cron: '@every 60s'
